### ISSUE TITLE
i lost all mony

### ISSUE THREAD

**Issue by lachlanmcglennon** [spencerbrake/Slot-Machine-Browser-Game-#1]
i got a 5 7s and ut did not give me any mony also the slot machine is too hard because i trued all the mony and lots it :((((((((((( make solt machin better and reward better too it not fun now too unlucky.

**Comment by spencerbrake** [comment]
> i got a 5 7s and ut did not give me any mony also the slot machine is too hard because i trued all the mony and lots it :((((((((((( make solt machin better and reward better too it not fun now too unlucky.

well this is a take on a classic slot machine and slot machines are notorious for taking peoples money, not winning every single spin. Also, 5 7s should result a win. If you could duplicate this and show me that its not working but my code seems to be correct.
